---
version: '2'
services:
  app:
    environment:
      DISCOURSE_HOSTNAME: forum.your.org
      DISCOURSE_SMTP_ADDRESS: smtp.sendgrid.net
      DISCOURSE_SMTP_PORT: '587'
      DISCOURSE_SMTP_USER_NAME: smtpuser
      DISCOURSE_SMTP_PASSWORD: password
      DISCOURSE_DEVELOPER_EMAILS: hostmaster@your.domain
      DISCOURSE_DB_PASSWORD: d15c0ur53
      DISCOURSE_DB_HOST: postgres-discourse
      DISCOURSE_REDIS_HOST: redis-discourse
    build: .
    ports:
      - "8080:80"
    depends_on:
      - postgres-discourse
      - redis-discourse
  redis-discourse:
    image: redis:3.2
  postgres-discourse:
    environment:
      POSTGRES_USER: discourse
      POSTGRES_PASSWORD: d15c0ur53
    image: postgres:9.4
