---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discourse
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: discourse
    spec:
      containers:
      - image: artsy/discourse:1.8.9
        name: discourse
        envFrom:
        - configMapRef:
            name: discourse-environment
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /shared
          name: discourse-data
      restartPolicy: Always
      volumes:
      - name: discourse-data
        persistentVolumeClaim:
          claimName: discourse-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discourse-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: discourse
  name: discourse
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
  selector:
    app: discourse
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discourse-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: discourse-redis
    spec:
      containers:
      - name: redis
        image: redis:3.2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: discourse-redis
  name: discourse-redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: discourse-redis
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discourse-postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: discourse-postgres
    spec:
      containers:
      - image: postgres:9.4
        name: postgres
        env:
        - name: POSTGRES_USER
          value: discourse
        - name: POSTGRES_PASSWORD
          value: d15c0ur53
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: discourse-postgres-data
      restartPolicy: Always
      volumes:
      - name: discourse-postgres-data
        persistentVolumeClaim:
          claimName: discourse-postgres-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discourse-postgres-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: discourse-postgres
  name: discourse-postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: discourse-postgres
  type: ClusterIP
