---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discourse
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: discourse
    spec:
      containers:
      - image: artsy/discourse:latest
        name: discourse
        envFrom:
        - configMapRef:
            name: discourse-environment
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /shared
          name: discourse-data
        imagePullPolicy: Always
      restartPolicy: Always
      volumes:
      - name: discourse-data
        persistentVolumeClaim:
          claimName: discourse-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discourse-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: discourse
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::MYSERVERCERTIFICATE"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
  name: discourse
spec:
  ports:
  - port: 443
    targetPort: 80
    name: https
    protocol: TCP
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
  selector:
    app: discourse
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-discourse
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-discourse
    spec:
      containers:
      - name: redis
        image: redis:3.2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-discourse
  name: redis-discourse
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app: redis-discourse
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-discourse
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-discourse
    spec:
      containers:
      - image: postgres:9.4
        name: postgres
        env:
        - name: POSTGRES_USER
          value: discourse
        - name: POSTGRES_PASSWORD
          value: d15c0ur53
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: postgres-discourse-data
      restartPolicy: Always
      volumes:
      - name: postgres-discourse-data
        persistentVolumeClaim:
          claimName: postgres-discourse-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-discourse-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-discourse
  name: postgres-discourse
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: postgres-discourse
  type: ClusterIP
