#!/bin/bash
exec 2>&1

if [[ ! -d /shared/log/rails ]]; then
  mkdir -p /shared/log/rails
fi
if [[ ! -d /shared/uploads ]]; then
  mkdir -p /shared/uploads
fi
if [[ ! -d /shared/backups ]]; then
  mkdir -p /shared/backups
fi

cd /var/www/discourse
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.1 ./bootstrap.sh
