#!/bin/bash

env > ~/boot_env

[ ! -z "$COMPRESS_BROTLI" ] && sed -i "s/. brotli/  brotli/" /etc/nginx/conf.d/discourse.conf || sed -i "s/. brotli/# brotli/" /etc/nginx/conf.d/discourse.conf

mkdir -p /var/log/nginx
chgrp -R www-data /var/log/nginx
chgrp www-data /var/log/nginx

chown -R discourse /var/www/discourse
chown -R discourse:www-data /shared/log/rails /shared/uploads /shared/backups

exec 2>&1
exec /usr/sbin/nginx
